### ISSUE TITLE
영문번역

### ISSUE THREAD

**Issue by keonkim** [Hanul/UPPERCASE#1]
UPPERCASE 를 배우는 김에 번역도 같이 시작했습니다.

학생이라 진행과정이 좀 느릴 수 있으니 양해 부탁드립니다.

번역과정은 아래에서 보실 수 있습니다.
https://github.com/keonkim/UPPERCASE.IO/tree/master/DOC/EN

**Comment by Hanul** [comment]
오마이갓!
이런 가뭄에 단비같은 존재가!!
너무나 반가운 소식이군요.
아직 한글 문서 자체도 100% 완벽하지 않으니 정보 주고받으며 진행해보죠.
기쁜 소식 전해주셔서 감사합니다.

**Comment by keonkim** [comment]
요즘 업뎃을 못해서 죄송합니다 ㅎ.. 한동안 쉬다가 이제 다시 번역작업 다시 시작하려고합니다. 제 학교 학생들에게도 알려서 사용인구를 조금 늘려보려고 합니다.

**Comment by Hanul** [comment]
언제든 환영입니다 :)
