### ISSUE TITLE
웹 소켓 접속이 안될 때는 어떤 트랜스포트를 이용하나요?

### ISSUE THREAD

**Issue by minhoryang** [Hanul/UPPERCASE#15]
[DOC/UPPERCASE-TRANSPORT.md](https://github.com/Hanul/UPPERCASE/blob/master/DOC/UPPERCASE-TRANSPORT.md) 읽어보고 있는데요.
Failback에 대한 내용은 기재되어 있지 않더라구요.

웹소켓으로 접속이 되지 않을 때는, 어떤 트랜스포트를 이용하도록 되어있나요?
웹소켓으로 접속이 되나, 통신환경이 원활하지 않을 때는 어떤가요?

**Comment by Hanul** [comment]
질문 감사합니다.
웹 소켓으로 접속이 되지 않으면 자동으로 Long Polling으로 접속하게 되어 있습니다.
또한 통신환경이 원할하지 않더라도 전송은 보장됩니다. (비록 딜레이가 있더라도)
만약 아예 통신이 끊어진 경우에는 재접속을 시도합니다.

**Comment by minhoryang** [comment]
답변 감사합니다!
관련 코드를 찾아보겠습니다! :)
