### ISSUE TITLE
using color attribute in UUI.FULL_INPUT

### ISSUE THREAD

**Issue by rrrfffrrr** [Hanul/UPPERCASE#22]
color attribute for UUI.FULL_INPUT is not working

TD({
	style : { 
		width : 70
	},
	c : UUI.FULL_INPUT({
		style : {
			color : '#fff',
			backgroundColor : '#161616',
			borderTop : '1px solid #fff',
			borderRight : '1px solid #fff',
			width : 70
		},
		name : 'writer',
		value : 'Noname'
	})
})

**Comment by Hanul** [comment]
아래와 같이 해보시겠어요?
```javascript
TD({
    c: UUI.FULL_INPUT({
        style: {
            backgroundColor: '#161616',
            borderTop: '1px solid #fff',
            borderRight: '1px solid #fff'
        },
        inputStyle: {
            color: '#fff',
            width: 70
        },
        name: 'writer',
        value: 'Noname'
    })
})
```
