### ISSUE TITLE
$lt and other operator is to be unknown operator

### ISSUE THREAD

**Issue by rrrfffrrr** [Hanul/UPPERCASE#25]
`test_Chat.MessageModel.find({
					filter : {
						$lt : {
							createTime : previousChatTime
						}
					}
				},
				recievenewdata);`

in the console log
[UPPERCASE-MODEL] `test_Chat.MessageModel.find` ERROR: MongoError: unknown top level operator: $lt

not only lt other operator like gt, gte, ... is to be unknown operator

**Comment by rrrfffrrr** [comment]
Example is wrong in the [UPPERCASE-DB.md](https://github.com/Hanul/UPPERCASE/blob/master/DOC/UPPERCASE-DB.md)

it should be rewrite

**Comment by Hanul** [comment]
맞습니다. 오류를 고쳐주셔서 감사합니다.
